spring:
  data:
    mongodb:
      uri: "${MONGODB_URI}"
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB

# Python API Configuration
python:
  api:
    url: ${PYTHON_API_URL}

# AI API Configuration
ai:
  api:
    url: ${AI_API_URL}

# JWT Properties
shadowise:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
