spring:
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      connection-pool:
        max-size: 100
        min-size: 5
        max-wait-time: 30000
        max-connection-life-time: 300000
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB

# JWT Properties
shadowise:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
