spring:
  application:
    name: shadowise-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

file:
  storage:
    path: file-storage