spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/shadowise"

  security:
    user:
      name: "admin"
      password: "admin"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Python API Configuration
python:
  api:
    url: http://localhost:5000

# JWT Properties
shadowise:
  app:
    jwtSecret: oRq8/8RJaQ1Rnqd32P7m85FWfBOMqtPFcD1cby6fLOKWEHf4iLSbkAvi/H+wCsS5F2cHX2LhUqfkYRcUBFVpNQ==
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000