spring:
  data:
    mongodb:
      uri: "${MONGODB_URI}"

# Python API Configuration
python:
  api:
    url: ${PYTHON_API_URL}

# JWT Properties
shadowise:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
